complete -c godwit-daemon -n "__fish_use_subcommand" -s q -l quiet -d 'Silence all output'
complete -c godwit-daemon -n "__fish_use_subcommand" -s v -l verbose -d 'Debug mode'
complete -c godwit-daemon -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c godwit-daemon -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c godwit-daemon -n "__fish_use_subcommand" -f -a "new" -d 'Start new task and schedule'
complete -c godwit-daemon -n "__fish_use_subcommand" -f -a "regress" -d 'Regress operation until killsignal sent'
complete -c godwit-daemon -n "__fish_use_subcommand" -f -a "die" -d 'Send killsignal'
complete -c godwit-daemon -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c godwit-daemon -n "__fish_seen_subcommand_from new" -s r -l refresh -d 'Discard all previous diffs'
complete -c godwit-daemon -n "__fish_seen_subcommand_from new" -s h -l help -d 'Prints help information'
complete -c godwit-daemon -n "__fish_seen_subcommand_from new" -s V -l version -d 'Prints version information'
complete -c godwit-daemon -n "__fish_seen_subcommand_from new" -s q -l quiet -d 'Silence all output'
complete -c godwit-daemon -n "__fish_seen_subcommand_from new" -s v -l verbose -d 'Debug mode'
complete -c godwit-daemon -n "__fish_seen_subcommand_from new" -f -a "trace" -d 'Trace an application state'
complete -c godwit-daemon -n "__fish_seen_subcommand_from new" -f -a "split" -d 'Split processess'
complete -c godwit-daemon -n "__fish_seen_subcommand_from new" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c godwit-daemon -n "__fish_seen_subcommand_from trace" -s h -l help -d 'Prints help information'
complete -c godwit-daemon -n "__fish_seen_subcommand_from trace" -s V -l version -d 'Prints version information'
complete -c godwit-daemon -n "__fish_seen_subcommand_from trace" -s r -l refresh -d 'Discard all previous diffs'
complete -c godwit-daemon -n "__fish_seen_subcommand_from trace" -s q -l quiet -d 'Silence all output'
complete -c godwit-daemon -n "__fish_seen_subcommand_from trace" -s v -l verbose -d 'Debug mode'
complete -c godwit-daemon -n "__fish_seen_subcommand_from split" -s h -l help -d 'Prints help information'
complete -c godwit-daemon -n "__fish_seen_subcommand_from split" -s V -l version -d 'Prints version information'
complete -c godwit-daemon -n "__fish_seen_subcommand_from split" -s r -l refresh -d 'Discard all previous diffs'
complete -c godwit-daemon -n "__fish_seen_subcommand_from split" -s q -l quiet -d 'Silence all output'
complete -c godwit-daemon -n "__fish_seen_subcommand_from split" -s v -l verbose -d 'Debug mode'
complete -c godwit-daemon -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c godwit-daemon -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c godwit-daemon -n "__fish_seen_subcommand_from help" -s r -l refresh -d 'Discard all previous diffs'
complete -c godwit-daemon -n "__fish_seen_subcommand_from help" -s q -l quiet -d 'Silence all output'
complete -c godwit-daemon -n "__fish_seen_subcommand_from help" -s v -l verbose -d 'Debug mode'
complete -c godwit-daemon -n "__fish_seen_subcommand_from regress" -s r -l refresh -d 'Discard all previous diffs'
complete -c godwit-daemon -n "__fish_seen_subcommand_from regress" -s h -l help -d 'Prints help information'
complete -c godwit-daemon -n "__fish_seen_subcommand_from regress" -s V -l version -d 'Prints version information'
complete -c godwit-daemon -n "__fish_seen_subcommand_from regress" -s q -l quiet -d 'Silence all output'
complete -c godwit-daemon -n "__fish_seen_subcommand_from regress" -s v -l verbose -d 'Debug mode'
complete -c godwit-daemon -n "__fish_seen_subcommand_from regress" -f -a "trace" -d 'Trace an application state'
complete -c godwit-daemon -n "__fish_seen_subcommand_from regress" -f -a "split" -d 'Split processess'
complete -c godwit-daemon -n "__fish_seen_subcommand_from regress" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c godwit-daemon -n "__fish_seen_subcommand_from trace" -s h -l help -d 'Prints help information'
complete -c godwit-daemon -n "__fish_seen_subcommand_from trace" -s V -l version -d 'Prints version information'
complete -c godwit-daemon -n "__fish_seen_subcommand_from trace" -s r -l refresh -d 'Discard all previous diffs'
complete -c godwit-daemon -n "__fish_seen_subcommand_from trace" -s q -l quiet -d 'Silence all output'
complete -c godwit-daemon -n "__fish_seen_subcommand_from trace" -s v -l verbose -d 'Debug mode'
complete -c godwit-daemon -n "__fish_seen_subcommand_from split" -s h -l help -d 'Prints help information'
complete -c godwit-daemon -n "__fish_seen_subcommand_from split" -s V -l version -d 'Prints version information'
complete -c godwit-daemon -n "__fish_seen_subcommand_from split" -s r -l refresh -d 'Discard all previous diffs'
complete -c godwit-daemon -n "__fish_seen_subcommand_from split" -s q -l quiet -d 'Silence all output'
complete -c godwit-daemon -n "__fish_seen_subcommand_from split" -s v -l verbose -d 'Debug mode'
complete -c godwit-daemon -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c godwit-daemon -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c godwit-daemon -n "__fish_seen_subcommand_from help" -s r -l refresh -d 'Discard all previous diffs'
complete -c godwit-daemon -n "__fish_seen_subcommand_from help" -s q -l quiet -d 'Silence all output'
complete -c godwit-daemon -n "__fish_seen_subcommand_from help" -s v -l verbose -d 'Debug mode'
complete -c godwit-daemon -n "__fish_seen_subcommand_from die" -s h -l help -d 'Prints help information'
complete -c godwit-daemon -n "__fish_seen_subcommand_from die" -s V -l version -d 'Prints version information'
complete -c godwit-daemon -n "__fish_seen_subcommand_from die" -s q -l quiet -d 'Silence all output'
complete -c godwit-daemon -n "__fish_seen_subcommand_from die" -s v -l verbose -d 'Debug mode'
complete -c godwit-daemon -n "__fish_seen_subcommand_from die" -f -a "trace" -d 'Trace an application state'
complete -c godwit-daemon -n "__fish_seen_subcommand_from die" -f -a "split" -d 'Split processess'
complete -c godwit-daemon -n "__fish_seen_subcommand_from die" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c godwit-daemon -n "__fish_seen_subcommand_from trace" -s h -l help -d 'Prints help information'
complete -c godwit-daemon -n "__fish_seen_subcommand_from trace" -s V -l version -d 'Prints version information'
complete -c godwit-daemon -n "__fish_seen_subcommand_from trace" -s q -l quiet -d 'Silence all output'
complete -c godwit-daemon -n "__fish_seen_subcommand_from trace" -s v -l verbose -d 'Debug mode'
complete -c godwit-daemon -n "__fish_seen_subcommand_from split" -s h -l help -d 'Prints help information'
complete -c godwit-daemon -n "__fish_seen_subcommand_from split" -s V -l version -d 'Prints version information'
complete -c godwit-daemon -n "__fish_seen_subcommand_from split" -s q -l quiet -d 'Silence all output'
complete -c godwit-daemon -n "__fish_seen_subcommand_from split" -s v -l verbose -d 'Debug mode'
complete -c godwit-daemon -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c godwit-daemon -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c godwit-daemon -n "__fish_seen_subcommand_from help" -s q -l quiet -d 'Silence all output'
complete -c godwit-daemon -n "__fish_seen_subcommand_from help" -s v -l verbose -d 'Debug mode'
complete -c godwit-daemon -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c godwit-daemon -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c godwit-daemon -n "__fish_seen_subcommand_from help" -s q -l quiet -d 'Silence all output'
complete -c godwit-daemon -n "__fish_seen_subcommand_from help" -s v -l verbose -d 'Debug mode'
