name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

strategy:
  matrix:
    os: [ubuntu-latest, windows-latest, macos-latest]

jobs:
  build-${{ matrix.os }}:
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/cargo@v1

    - name: Build daemon
      with:
        command: build
        args: --release --all-features

    - name: Run daemon tests
      with:
        command: test
        args: --verbose
